# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0004_datalayer_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayer',
            name='maps',
            field=models.ManyToManyField(related_name='DataLayer', to='leaflet_storage.Map'),
        ),
    ]
