# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0005_auto_20170512_1250'),
        ('leaflet_storage', '0004_tilelayer_tms'),
    ]

    operations = [
    ]
