# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0006_merge_20180505_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование типа карты')),
            ],
            options={
                'verbose_name': 'Тип карты',
            },
        ),
        migrations.AddField(
            model_name='map',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaflet_storage.CategoryMap', verbose_name='категория  карты'),
        ),
    ]
