# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('leaflet_storage', '0007_auto_20180703_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
