# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-13 05:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0009_auto_20180726_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='style',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='mapbox style'),
        ),
    ]
