# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 06:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0010_map_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='style',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'center': [37.627487, 55.741028], 'glyphs': 'mapbox://fonts/mapbox/{fontstack}/{range}.pbf', 'layers': [], 'name': '', 'sources': {}, 'sprite': 'http://localhost:8000/static/sprite/sprite', 'varsion': 8, 'zoom': 8}, verbose_name='mapbox style'),
        ),
    ]
